### ISSUE TITLE
编译合约报错 Starting js4eos_bg2 daemon... over

### ISSUE THREAD

**Issue by mokeychan** [itleaks/js4eos#11]
λ js4eos reset
Starting js4eos_bg2 daemon... 就结束了 没有错误，也没有编译后的wast/wasm,abi文件。

**Comment by itleaks** [comment]
重启机器试试

**Comment by mokeychan** [comment]
谢谢您的答复，已经解决了。使用eos的工具，但是js4eos尚不清楚原因，重启有试过，我怀疑是网络问题。
